### PR TITLE
Simplify import statements 

### PR DESCRIPTION
**Pull request by passalis**
This PR aims to simplify the import statments by exposing the commonly used classes and functions in the each module's `__init.py__` file following #132.

My suggestion is to go from:

```python
from opendr.perception.pose_estimation.lightweight_open_pose.lightweight_open_pose_learner import \
    LightweightOpenPoseLearner
```

to simply

```python
from opendr.perception.pose_estimation import LightweightOpenPoseLearner
```

### CODE REVIEW

**Comment by ad-daniel** [comment]
What has been done:
- Simplify import statements for all tools
- Use simplified statements in tests, demos, and updated examples provided in documentation
- Separation of tools in the docs according to their domain (analogous to how they are structured in the code), it looks like [this](https://github.com/tasostefas/opendr_internal/blob/simplify_api/docs/reference/index.md) now (feedback welcome)
- Replace 2-space with `\` for new line in docs. Using spaces wasn't a great idea, especially if you use a editor that eliminates trailing spaces automatically when you save.
- Improved consistency of docs (filenames use dash instead of underscore, formatting, ...)

**Comment by ad-daniel** [comment]
@passalis since it's your PR you can't review it, but would be nice if you could take a look, or @vniclas since we need 2 reviews regardless

**Comment by passalis** [comment]
thanks @ad-daniel !!! At first glance seems very nice! I will look into this later this evening and I will let you know and/or directly commit if there is something to change.

**Comment by passalis** [comment]
Hi @ad-daniel, it seems fine to me. Thank you! My suggestion is to merge this as soon as possible (I cannot review this since I created this PR) and require using this kind of import mechanism for all the new tools. I can also add a brief description of this in the wiki in the section where we describe the requirements for contributing a new tool.

**Review by omichel — APPROVED** [review]

**Review by ad-daniel — APPROVED** [review]

**Pull request merged**
