### PR TITLE
Fix EdgeSpeechNets target class and test

### PR DESCRIPTION
**Pull request by jovaroo**
Related to issue #62, fixes the tests printing unnecessary warnings.

Also fixes the implementation to use the Category target class instead of a special SpeechCommand, and removes the unnecessary code created for that earlier.

### CODE REVIEW

**Review by passalis — COMMENTED** [review]
Thanks for this PR. Please also remove the corresponding documentation from *engine-target.md*, since SpeechCommand is no longer used.

**Comment by jovaroo** [comment]
@passalis I have now removed the unnecessary documentation, and the PR is otherwise ready!

**Review by passalis — APPROVED** [review]
Thanks! Seems fine to me.

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you.

However, it seems that currently the `TEST Edge Speech Nets Learner` is not printing anything at all. This could be misleading for debugging it later because it is not clear if the test has run successfully, it failed or didn't run at all.

**Pull request merged**
