### PR TITLE
tests are simplified

### PR DESCRIPTION
**Pull request by negarhdr**
This PR simplifies the tests of `stbln` and `stgcn` methods (as much as possible) to address issue #167 by lowering the memory load.

### CODE REVIEW

**Review by passalis — APPROVED** [review]
Thank you.

**Comment by ad-daniel** [comment]
I'm not against keeping those tests even if the same functionality is executed within other methods, especially in case of problems we would more easily be able to narrow it down. I've made a few tests and it seems the only change we really need is lowering the `batch_size` as you did. Doing so drops the ram load by around a factor of 2, which is plenty enough.

Also, when we merge this PR we should remove [this](https://github.com/tasostefas/opendr_internal/blob/4e730b9ced96a056b64980e4bef5ea8c971e075d/.github/workflows/tests_sources.yml#L55) line

**Comment by ad-daniel** [comment]
I'll run it 2 or 3 times and see if there are issues, but I suspect this might be enough

**Comment by ad-daniel** [comment]
Looks like the 2nd round the tests failed, but not because of the change made, but rather heart anomaly detection (gru):

```
 ./opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sklearn/metrics/classification.py:1436: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  precision = _prf_divide(tp_sum, pred_sum,
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sklearn/metrics/classification.py:1438: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  recall = _prf_divide(tp_sum, true_sum,
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sklearn/metrics/classification.py:1436: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  precision = _prf_divide(tp_sum, pred_sum,
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/sklearn/metrics/classification.py:1438: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  recall = _prf_divide(tp_sum, true_sum,
./opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/torch/autograd/__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(
.....F...

======================================================================

FAIL: test_fit (gated_recurrent_unit.test_gated_recurrent_unit_learner.TestGatedRecurrentUnitLearner)
**********************************
----------------------------------------------------------------------
TEST Attention Neural Bag-of-Feature Learner
Traceback (most recent call last):
**********************************
  File "/home/runner/work/opendr_internal/opendr_internal/tests/sources/tools/perception/heart_anomaly_detection/gated_recurrent_unit/test_gated_recurrent_unit_learner.py", line 82, in test_fit
Pretrained model downloaded to the following directory
    self.assertFalse(torch.equal(old_weight, new_weight),
/tmp/tmp4eby43my
AssertionError: True is not false : Model parameters did not change after running fit.
Pretrained model is loaded successfully


----------------------------------------------------------------------

Ran 11 tests in 73.154s
**********************************

TEST Gated Recurrent Unit Learner
FAILED (failures=1)
```

I've re-run it like 5 times locally but I can't reproduce. Could be a fluke.

**Review by ad-daniel — APPROVED** [review]
Appears to be sufficient to lower the batch size. Since other PR are failing because of this error, I think we can merge. We'll need to keep an eye out for the heart anomaly test failing though, if it happens again we might need to look into it.

**Comment by negarhdr** [comment]
@passalis Would you please approve this again, so that I can merge?

**Review by passalis — APPROVED** [review]

**Pull request merged**
