### PR TITLE
Skeleton based action recognition

### PR DESCRIPTION
**Pull request by negarhdr**
This PR adds two learners (which train and evaluate a baseline model and three proposed models) for skeleton-based human action recognition. 

- A new data type named `SkeletonSequence` is added to the `engine.data.py` and a new target class named `ActionCategory` is added to `engine.target.py`. 

- The learners' implementation follows the provided template and sufficient tests are provided for all the functions which will be directly called by the user including, `fit()`, `eval()`, `infer()`, `save()`, `load()`, `optimize()`, `multi_stream_eval()`, `network_builder()`.

### CODE REVIEW

**Comment by passalis** [comment]
@negarhdr testing is now available again. So, when you are ready, you can use the "test sources" label to run the style checks and "test tools" to run the tool tests.

**Comment by negarhdr** [comment]
@passalis , @stefaniapedrazzi 
All the comments for this PR are addressed and it is ready to review. However, the API tests are failed after a while for STGCN fit function with this message: 

`/home/runner/work/_temp/ce3bf0a2-831e-4c0f-a74c-7d95f0238a4c.sh: line 8:  3283 Killed                  
python -m unittest discover -s tests/sources
Error: Process completed with exit code 137.`

I test it on my own computer and it works without any problem. The dataset is very small (10 samples only) and it trains for only 1 epoch.
Could you please check it out and let me know if the problem is from my side? 
Thank you.

**Comment by stefaniapedrazzi** [comment]
One thing you could try in this branch is to temporary disable all the other tests.
This can be easily done by removing the `__init__.py` files in the other folder folder.
So you could run just your tests and check if there is maybe a conflict with some other.

Another one is try to run the tests in a clean environment and checking that you don't have any additional file or folder in the local  repository.

When I run them locally I also get some errors:
* In `Test STGCN optimize function`:
    ```
    Error: ./tests/sources/tools/perception/skeleton_based_action_recognition/skeleton_based_action_recognition_temp/stgcn_nturgbd_cv_joint - Is a directory.
    ```
* in `test_save_load_onnx` functions for all the different methods (here is just one of the 4 reported errors):
```
ERROR: test_save_load_onnx (skeleton_based_action_recognition.test_pstgcn.TestSkeletonBasedActionRecognition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stefi/develop/opendr_internal/tests/sources/tools/perception/skeleton_based_action_recognition/test_pstgcn.py", line 194, in test_save_load_onnx
    self.pstgcn_action_classifier.save(path=os.path.join(self.temp_dir, self.experiment_name),
  File "/home/stefi/develop/opendr_internal/src/opendr/perception/skeleton_based_action_recognition/progressive_spatio_temporal_gcn_learner.py", line 653, in save
    shutil.copy2(os.path.join(self.parent_dir, self.experiment_name, "onnx_model_temp.onnx"),
  File "/home/stefi/develop/opendr_internal/venv/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/stefi/develop/opendr_internal/venv/lib/python3.8/shutil.py", line 244, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: './tests/sources/tools/perception/skeleton_based_action_recognition/skeleton_based_action_recognition_temp/pstgcn_nturgbd_cv_joint/onnx_model_temp.onnx' and './tests/sources/tools/perception/skeleton_based_action_recognition/skeleton_based_action_recognition_temp/pstgcn_nturgbd_cv_joint/onnx_model_temp.onnx' are the same file
```
Don't you get the same errors?

If it would be posible to reduce the logs of the tests (all of them not just the new ones in this folder), then it will also be easier to debug issues like this.

**Comment by negarhdr** [comment]
> One thing you could try in this branch is to temporary disable all the other tests.
> This can be easily done by removing the `__init__.py` files in the other folder folder.
> So you could run just your tests and check if there is maybe a conflict with some other.
> 
> Another one is try to run the tests in a clean environment and checking that you don't have any additional file or folder in the local repository.
> 
> When I run them locally I also get some errors:
> 
> * In `Test STGCN optimize function`:
>   ```
>   Error: ./tests/sources/tools/perception/skeleton_based_action_recognition/skeleton_based_action_recognition_temp/stgcn_nturgbd_cv_joint - Is a directory.
>   ```
> * in `test_save_load_onnx` functions for all the different methods (here is just one of the 4 reported errors):
> 
> ```
> ERROR: test_save_load_onnx (skeleton_based_action_recognition.test_pstgcn.TestSkeletonBasedActionRecognition)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/stefi/develop/opendr_internal/tests/sources/tools/perception/skeleton_based_action_recognition/test_pstgcn.py", line 194, in test_save_load_onnx
>     self.pstgcn_action_classifier.save(path=os.path.join(self.temp_dir, self.experiment_name),
>   File "/home/stefi/develop/opendr_internal/src/opendr/perception/skeleton_based_action_recognition/progressive_spatio_temporal_gcn_learner.py", line 653, in save
>     shutil.copy2(os.path.join(self.parent_dir, self.experiment_name, "onnx_model_temp.onnx"),
>   File "/home/stefi/develop/opendr_internal/venv/lib/python3.8/shutil.py", line 435, in copy2
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "/home/stefi/develop/opendr_internal/venv/lib/python3.8/shutil.py", line 244, in copyfile
>     raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
> shutil.SameFileError: './tests/sources/tools/perception/skeleton_based_action_recognition/skeleton_based_action_recognition_temp/pstgcn_nturgbd_cv_joint/onnx_model_temp.onnx' and './tests/sources/tools/perception/skeleton_based_action_recognition/skeleton_based_action_recognition_temp/pstgcn_nturgbd_cv_joint/onnx_model_temp.onnx' are the same file
> ```
> 
> Don't you get the same errors?
> 
> If it would be posible to reduce the logs of the tests (all of them not just the new ones in this folder), then it will also be easier to debug issues like this.



Thanks for the comments. These errors were mainly related to the clean-ups after the tests and they are resolved now. I test the code on our own server and I don't get any more errors or warnings. However, the tests are still failed here when it starts testing the ST-GCN method with this message: 

`/home/runner/work/_temp/add8f37b-fdcb-4171-ad50-a3f5e0c45922.sh: line 8:  3674 Killed `

Both learners were passing all the tests here before. I don't know what could be the reason of this failure now.

**Comment by stefaniapedrazzi** [comment]
> Thanks for the comments. These errors were mainly related to the clean-ups after the tests and they are resolved now. I test the code on our own server and I don't get any more errors or warnings. However, the tests are still failed here when it starts testing the ST-GCN method with this message:
``/home/runner/work/_temp/add8f37b-fdcb-4171-ad50-a3f5e0c45922.sh: line 8: 3674 Killed``
Both learners were passing all the tests here before. I don't know what could be the reason of this failure now.

In general, tests are too verbose to get meaningful errors from the CI logs.
I'm now trying to ask every contributors to reduce the verbosity of the tests to improve it.

I also tried to disable a test that is known to be broken on the master branch.
Let we see if the tests pass successfully after this.
I tested locally (just the skeleton_based_action_recognition ones) and now they work correctly for me.

**Comment by negarhdr** [comment]
> It seems there may be conflicts with other tests.
> 
> What I can suggest you it to try to debug the issue by disabling other tests and try to identify which one is causing the conflict.

It seems that the "Activity Recognition" branch causes the conflict (All the tests are passed when the tests of that branch are disabled). However, from the logs, it is not clear what is the reason for the conflict exactly.

**Comment by negarhdr** [comment]
Failing again even when I disable all the other tests. I think it might be a memory issue on this server, not sufficient RAM memory, or garbage collector's inconsistency.

**Comment by stefaniapedrazzi** [comment]
Please resolve the conflicts and update to master to check if the new testing system is fixing the test errors.
You also have to add the test `skeleton_based_action_recognition` here:
https://github.com/tasostefas/opendr_internal/blob/7496b7356fd492b0fb9c9ba2e81111e95aac8140/.github/workflows/tests_sources.yml#L66

**Comment by negarhdr** [comment]
> Please resolve the conflicts and update to master to check if the new testing system is fixing the test errors.
> You also have to add the test `skeleton_based_action_recognition` in this list:
> https://github.com/tasostefas/opendr_internal/blob/7496b7356fd492b0fb9c9ba2e81111e95aac8140/.github/workflows/tests_sources.yml#L66

@stefaniapedrazzi when I update the `opendr_internal/.github/workflows/tests_sources.yml` file, the Push is rejected! 
Isn't it the case that this file can only be modified by code owners?

**Comment by stefaniapedrazzi** [comment]
> @stefaniapedrazzi when I update the opendr_internal/.github/workflows/tests_sources.yml file, the Push is rejected!
Isn't it the case that this file can only be modified by code owners?

It would be very helpful to also see the log you receive when the push is rejected.
I don't think that only code owners can modify it, but I'm not an administrator of this repository so I cannot check the settings.
How do you perform the git actions? Directly from a terminal or using some applications?
If you are using an applications, could you please try directly from a terminal?

**Comment by passalis** [comment]
I think that the file can be edited by anyone (e.g., Lukas is not a codeowner and he edited this file). Can you provide more details regarding the reject? Please also check that you editing the file on your branch and not in the master branch.

**Comment by negarhdr** [comment]
Problem is solved. It was related to my personal access token. 
All the tests are passed and the branch is ready to be merged.

**Comment by stefaniapedrazzi** [comment]
Could you please also update the documentation index by adding your newly added documentation page?
https://github.com/tasostefas/opendr_internal/blob/master/docs/reference/index.md

Otherwise now everything is fine for me.

**Comment by negarhdr** [comment]
> Could you please also update the documentation index by adding your newly added documentation page?
> https://github.com/tasostefas/opendr_internal/blob/master/docs/reference/index.md
> 
> Otherwise now everything is fine for me.

@stefaniapedrazzi Index.md is updated.

**Review by stefaniapedrazzi — APPROVED** [review]
Thank you!

**Review by passalis — APPROVED** [review]
Thank you!

**Pull request merged**
