### PR TITLE
Face recognition ros

### PR DESCRIPTION
**Pull request by Pavlos-Tosidis**
Added ROS support for FaceRecognition.
Updated corresponding ReadME.
Fixed an issue in focal.py

### CODE REVIEW

**Comment by Pavlos-Tosidis** [comment]
Need some tweaking on FTP files to adapt to save/load changes, not ready for review yet

**Comment by stefaniapedrazzi** [comment]
I convert this PR to draft.
Please change the status when it is ready for review.

**Comment by ad-daniel** [comment]
@Pavlos-Tosidis Hi, what is the status of this PR?

**Comment by Pavlos-Tosidis** [comment]
Closed as duplicate

**Pull request closed without merging**
